### ISSUE TITLE
Howdy from "fattie" !

### ISSUE THREAD

**Issue by smhk** [RemyRM/Unity360RecorderExample#1]
Hi @RemyRM !  Really sorry to bother you here, I am your acquaintance from Stackoverflow!!!

To keep it brief, we were wondering if you ever do any freelance ??!

BTW my email is on my profile, github.com/smhk ... again sorry to bother you, hope to hear!  Cheers ...

**Comment by RemyRM** [comment]
All good. I have send a reply to your email.
